### ISSUE TITLE
parsing errors

### ISSUE THREAD

**Issue by ulf1** [ulf1/treesimi#45]
this cases parsing erros

```
tree = [(0, 1, 'nk'), (1, 2, 'sb'), (2, 2, 'ROOT'), (3, 2, 'pd'), (4, 2, 'punct')]
ts.adjac_to_nested_with_attr(tree)

tree = [(0, 1, 'nk'), (1, 2, 'sb'), (2, 2, 'ROOT'), (3, 4, 'nk'), (4, 2, 'oa'), (5, 2, 'punct')]
ts.adjac_to_nested_with_attr(tree)
```

=> These trees have the wrong presentation

**Comment by ulf1** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uh/projects/pkgdev/nlptasks/.venv/lib/python3.6/site-packages/treesimi/convert.py", line 219, in adjac_to_nested_with_attr
    nested = adjac_to_nested([(i, p) for i, p, _ in adjac])
  File "/Users/uh/projects/pkgdev/nlptasks/.venv/lib/python3.6/site-packages/treesimi/convert.py", line 107, in adjac_to_nested
    adjac, parent_id=parent_id, lft=1, depth=0, nested=[])
UnboundLocalError: local variable 'parent_id' referenced before assignment
```

**Comment by ulf1** [comment]
The bug is here https://github.com/ulf1/treesimi/blob/f28b2b5bb7e27a504ff546f7b504bf3f226082f8/treesimi/convert.py#L102

**Comment by ulf1** [comment]
the trees didn't specify the root's parent with ID=0
